import Link from 'next/link';
import { notFound } from 'next/navigation';
import { getAlert, getLatestBrief } from '@/lib/queries';
import { isUuid, formatUsd, formatDateTime } from '@/lib/format';
import { JsonView } from '@/components/JsonView';

export const dynamic = 'force-dynamic';

function asList(value: unknown): unknown[] {
  return Array.isArray(value) ? value : [];
}

export default async function BriefPage({ params }: { params: { id: string } }) {
  if (!isUuid(params.id)) {
    notFound();
  }

  const alert = await getAlert(params.id);
  if (!alert) {
    notFound();
  }

  const brief = await getLatestBrief(alert.id);
  if (!brief) {
    notFound();
  }

  const attackChain = asList(brief.attack_chain);
  const mitreTechniques = asList(brief.mitre_techniques);
  const recommendedActions = asList(brief.recommended_actions);
  const openQuestions = asList(brief.open_questions);
  const citedLogIds = asList(brief.cited_log_ids);

  return (
    <div className="space-y-6">
      <div>
        <Link href={`/alerts/${alert.id}`} className="text-sm text-blue-700 hover:underline">
          &larr; Back to alert
        </Link>
        <h1 className="mt-1 text-2xl font-semibold">Investigation brief</h1>
        <p className="text-sm text-slate-500">
          Generated by <span className="font-medium">{brief.provider_model}</span> &middot;{' '}
          {formatDateTime(brief.created_at)} &middot; cost {formatUsd(brief.cost_usd, 6)} (
          {brief.tokens_in} in / {brief.tokens_out} out tokens)
        </p>
      </div>

      <section className="rounded-md border border-slate-200 p-4">
        <h2 className="mb-2 text-lg font-medium">Summary</h2>
        <p className="whitespace-pre-wrap text-sm">{brief.summary}</p>
      </section>

      <section className="rounded-md border border-slate-200 p-4">
        <h2 className="mb-2 text-lg font-medium">Attack chain</h2>
        {attackChain.length === 0 ? (
          <p className="text-sm text-slate-500">No attack chain steps recorded.</p>
        ) : (
          <ol className="list-decimal space-y-2 pl-5 text-sm">
            {attackChain.map((step, i) => (
              <li key={i}>
                <JsonView data={step} />
              </li>
            ))}
          </ol>
        )}
      </section>

      <section className="rounded-md border border-slate-200 p-4">
        <h2 className="mb-2 text-lg font-medium">Cited log lines</h2>
        {/* Correlation UI is out of scope — these are opaque ids for now, as expected. */}
        {citedLogIds.length === 0 ? (
          <p className="text-sm text-slate-500">No cited log line ids.</p>
        ) : (
          <div className="flex flex-wrap gap-2">
            {citedLogIds.map((id, i) => (
              <span
                key={i}
                className="rounded border border-slate-300 bg-slate-100 px-2 py-0.5 font-mono text-xs"
              >
                {String(id)}
              </span>
            ))}
          </div>
        )}
      </section>

      <section className="rounded-md border border-slate-200 p-4">
        <h2 className="mb-2 text-lg font-medium">MITRE techniques</h2>
        {mitreTechniques.length === 0 ? (
          <p className="text-sm text-slate-500">None listed.</p>
        ) : (
          <div className="flex flex-wrap gap-2">
            {mitreTechniques.map((t, i) => (
              <span
                key={i}
                className="rounded border border-indigo-300 bg-indigo-50 px-2 py-0.5 text-xs text-indigo-800"
              >
                {typeof t === 'string' ? t : JSON.stringify(t)}
              </span>
            ))}
          </div>
        )}
      </section>

      <section className="rounded-md border border-slate-200 p-4">
        <h2 className="mb-2 text-lg font-medium">Recommended actions</h2>
        {recommendedActions.length === 0 ? (
          <p className="text-sm text-slate-500">None listed.</p>
        ) : (
          <ul className="list-disc space-y-1 pl-5 text-sm">
            {recommendedActions.map((a, i) => (
              <li key={i}>{typeof a === 'string' ? a : JSON.stringify(a)}</li>
            ))}
          </ul>
        )}
      </section>

      <section className="rounded-md border border-slate-200 p-4">
        <h2 className="mb-2 text-lg font-medium">Open questions</h2>
        {openQuestions.length === 0 ? (
          <p className="text-sm text-slate-500">None listed.</p>
        ) : (
          <ul className="list-disc space-y-1 pl-5 text-sm">
            {openQuestions.map((q, i) => (
              <li key={i}>{typeof q === 'string' ? q : JSON.stringify(q)}</li>
            ))}
          </ul>
        )}
      </section>
    </div>
  );
}
